# Generated by Django 3.0.6 on 2020-05-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_horario', models.DateTimeField()),
                ('hora_inicio', models.DateTimeField()),
                ('hora_termino', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sala', models.CharField(max_length=30)),
                ('piso_sala', models.IntegerField()),
                ('descripcion_sala', models.TextField(max_length=500)),
                ('estado_sala', models.BooleanField()),
            ],
        ),
    ]
