# Generated by Django 3.0.6 on 2020-05-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MantenedorSalas', '0005_auto_20200521_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='fecha_horario',
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_termino',
            field=models.DateTimeField(),
        ),
    ]
