# Generated by Django 3.0.6 on 2020-05-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MantenedorSalas', '0006_auto_20200521_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='disponibilidad',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
