# Generated by Django 3.0.6 on 2020-05-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MantenedorSalas', '0007_sala_disponibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='fecha',
            field=models.DateField(default='2020-05-02'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_termino',
            field=models.TimeField(),
        ),
    ]
