# Generated by Django 3.0.6 on 2020-06-15 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MantenedorSalas', '0009_auto_20200615_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='sala',
        ),
        migrations.AddField(
            model_name='horario',
            name='sala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='MantenedorSalas.Sala'),
            preserve_default=False,
        ),
    ]
