# Generated by Django 3.0.6 on 2020-05-21 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MantenedorSalas', '0002_auto_20200521_1831'),
        ('MantenedorSolicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='id_sala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MantenedorSalas.Sala'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='descripcion',
            field=models.TextField(max_length=200),
        ),
    ]
