# Generated by Django 3.0.6 on 2020-05-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MantenedorSolicitudes', '0003_auto_20200522_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='hora_final',
            new_name='hora_termino',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='codigo',
            field=models.CharField(default='202005133254', max_length=15),
            preserve_default=False,
        ),
    ]
