# Generated by Django 3.0.6 on 2020-05-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MantenedorSolicitudes', '0005_auto_20200523_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='respuesta',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
