# Generated by Django 3.0.6 on 2020-06-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MantenedorSolicitudes', '0006_solicitud_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado_solicitud',
            field=models.CharField(choices=[('a', 'Aceptada'), ('r', 'Rechazada'), ('e', 'No Vista')], default='e', max_length=2),
        ),
    ]
