# Generated by Django 3.0.6 on 2020-05-21 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MantenedorSalas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='edificio',
            field=models.CharField(default='p.a.o', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sala',
            name='horarios',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MantenedorSalas.Horario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sala',
            name='sede',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
