# Generated by Django 3.0.6 on 2020-05-22 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MantenedorSalas', '0002_auto_20200521_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='horarios',
        ),
        migrations.AddField(
            model_name='horario',
            name='sala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='MantenedorSalas.Sala'),
            preserve_default=False,
        ),
    ]
