# Generated by Django 3.0.6 on 2020-05-24 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MantenedorSalas', '0008_auto_20200523_2118'),
        ('MantenedorSolicitudes', '0004_auto_20200522_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='id_sala',
            new_name='sala',
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='hora_termino',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='horario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='MantenedorSalas.Horario'),
            preserve_default=False,
        ),
    ]
