# Generated by Django 3.0.6 on 2020-05-21 22:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MantenedorUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_usuario', models.CharField(max_length=15, unique=True)),
                ('telefono', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(729000000)])),
                ('fecha_nacimiento', models.DateField(default='2001-10-01')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
